### ISSUE TITLE
What's the point of this?

### ISSUE THREAD

**Issue by Chara-Reborn** [NuVanDibe/XCI-to-Split-NSP#1]
Isn't it smarter to use USB install v.i.a TinFoil anyways? Faster and can handle the whole file? 🤔

**Comment by NuVanDibe** [comment]
This is just an alternate solution is all. Not everyone has a USB drive or can be bothered to go out and buy one or dig through their drawer to find their own. I also am under the impression that not all USB drives are compatible, though most are.
